name: CI Pipeline

# Triggers the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Add steps here to install dependencies, build, and test your project
    # Below are placeholders. Replace them with your actual commands.

    # Example: Installing dependencies
    - name: Install dependencies
      run: echo "Replace this with a command to install dependencies"

    # Example: Building the application
    - name: Build the application
      run: echo "Replace this with a command to build your application"

    # Example: Running tests
    - name: Run tests
      run: echo "Replace this with a command to run tests"
